#!/bin/bash

# This script perform portainer-ce installation. 
# Portainer Community Edition is a lightweight service delivery platform for containerized applications that can be used to manage Docker, Swarm environments.
# Usage: ./install-portainer
# Auteur: Helmut

# Variable
ipv4=$(ip addr show $(ip route | awk '/default/ { print $5 }') | grep "inet" | head -n 1 | awk '/inet/ {print $2}' | cut -d'/' -f1);
logFile="install-portainer.log";

# This function print the actual date and time 
function now(){
    echo $(date +%Y-%M-%d---%H:%M:%S);
    return 0;
}

# This function print a message given in parameter
function printM(){
    if [ $# -eq 0 ]; then
        echo -e "This function require an argument. Usage: $FUNCNAME \"Your message here\"";
        exit 1;
    else
        echo -e $1;
    fi
}

# This function print an error given in parameter
function printE(){
    if [ $# -eq 0 ]; then
        echo -e "This function require an argument. Usage: $0 'Your text here'";
    else
        echo -e $1;
    fi
    exit 1;
}

# This function check the last command execution. It stop the script if command status isn't 0.
function checkLastCommandStatus(){
    if [ $? -ne 0 ]; then
        printE "Something spent wrong. See ./$logFile for more information.";
        exit 1;       
    fi
}

# This function perform the portainer installation in docker standalone environment
function standalone(){
    printM "$(now) | Start Portainer Deployment" | tee $logFile;

    printM "$(now) | Volume for portainer" >> $logFile;
    docker volume create portainer_data >> $logFile 2>&1;
    checkLastCommandStatus;

    printM "$(now) | Start portainer" >> $logFile;
    docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest  >> $logFile 2>&1;
    checkLastCommandStatus;

    printM "$(now) | Your Portainer deployment ended. Login at https://$ipv4:9443. See ./$logFile for more information.";
}

function main(){
    standalone;
}

# Run the main funtion
docker --version >> /dev/null;

if [ $? -ne 0 ]; then
    printE "You must have Docker installed before deploy portainer";
else
    main;
fi